apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
