apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-test
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
